services:
  pitcher-analyzer:
    build:
      context: .
      args:
        - HTTP_PROXY=http://proxy.wal-mart.com:8080
        - HTTPS_PROXY=http://proxy.wal-mart.com:8080
        - NO_PROXY=localhost,127.0.0.1
    ports:
      - "8503:8501"
    volumes:
      - ./credentials:/app/credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service-account.json
      - HTTP_PROXY=http://proxy.wal-mart.com:8080
      - HTTPS_PROXY=http://proxy.wal-mart.com:8080
      - NO_PROXY=localhost,127.0.0.1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3 