name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - v2-docker-deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: baseball-pitcher-analyzer
        
    - name: Build and push Docker image
      run: |
        gcloud auth configure-docker us-docker.pkg.dev
        docker build --platform linux/amd64 -t us-docker.pkg.dev/baseball-pitcher-analyzer/gcr.io/pitcher-analyzer:latest .
        docker push us-docker.pkg.dev/baseball-pitcher-analyzer/gcr.io/pitcher-analyzer:latest
        
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy pitcher-analyzer \
          --project baseball-pitcher-analyzer \
          --image us-docker.pkg.dev/baseball-pitcher-analyzer/gcr.io/pitcher-analyzer:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated 