[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
address = "0.0.0.0"
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
